### ISSUE TITLE
Data download problem

### ISSUE THREAD

**Issue by ravindraji4** [bzdfzfer/Allan_Standard_Deviation_Analysis#1]
loiter_mpu6050.mat is corrupted, I downloaded it twice and matlab had the following error.
>> load('loitor_mpu6050.mat')
Warning: Unexpected end-of-file while reading
compressed data. 
Error using load
Cannot read file
Regarding the file Static_3DM.mat, the Baidu is asking to download their down-loader. Is it possible to download it without the down-loader.

**Comment by bzdfzfer** [comment]
Thanks for the reply! I will reupload them in another way. Please let me know if this onedrive link is OK.

**Comment by ravindraji4** [comment]
It works perfectly fine, Thank you very much for uploading the data :) :+1:
